# Generated by Django 3.0.6 on 2020-05-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('specialization', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gander', models.CharField(max_length=256)),
                ('age', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=128)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor')),
            ],
        ),
    ]
